{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "k8s-operator-hermes-agent.controllerManagerLabels" . | nindent 4 }}
    {{- with .Values.metrics.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.metrics.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "k8s-operator-hermes-agent.controllerManagerSelectorLabels" . | nindent 4 }}
{{- end }}
