{{- if and .Values.webhook.enabled .Values.certManager.enabled .Values.webhook.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "k8s-operator-hermes-agent.controllerManagerLabels" . | nindent 4 }}
  name: {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "allow-webhook-traffic" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "k8s-operator-hermes-agent.controllerManagerSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.webhook.port }}
          protocol: TCP
{{- end }}
