{{- $metricsTLSManaged := include "k8s-operator-hermes-agent.metricsTLSManaged" . }}
{{- if $metricsTLSManaged }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
{{ include "k8s-operator-hermes-agent.commonLabels" . | nindent 4 }}
  name: {{ include "k8s-operator-hermes-agent.metricsServingCertificateName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}.{{ .Release.Namespace }}.svc
  - {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "k8s-operator-hermes-agent.selfSignedIssuerName" . }}
  secretName: {{ include "k8s-operator-hermes-agent.metricsServingCertificateSecretName" . }}
{{- end }}
