{{- if or (include "k8s-operator-hermes-agent.webhookTLSManaged" .) (include "k8s-operator-hermes-agent.metricsTLSManaged" .) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
{{ include "k8s-operator-hermes-agent.commonLabels" . | nindent 4 }}
  name: {{ include "k8s-operator-hermes-agent.selfSignedIssuerName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
