{{- if or (include "k8s-operator-hermes-agent.webhookTLSManaged" .) (include "k8s-operator-hermes-agent.metricsTLSManaged" .) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "k8s-operator-hermes-agent.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "k8s-operator-hermes-agent.selfSignedIssuerName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
