{{- $webhookTLSManaged := include "k8s-operator-hermes-agent.webhookTLSManaged" . }}
{{- if $webhookTLSManaged }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
{{ include "k8s-operator-hermes-agent.commonLabels" . | nindent 4 }}
  name: {{ include "k8s-operator-hermes-agent.webhookServingCertificateName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "webhook-service" "context" $) }}.{{ .Release.Namespace }}.svc
  - {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "webhook-service" "context" $) }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "k8s-operator-hermes-agent.selfSignedIssuerName" . }}
  secretName: webhook-server-cert
{{- end }}
