{{- if and .Values.webhook.enabled .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "k8s-operator-hermes-agent.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "serving-cert" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "webhook-service" "context" $) }}.{{ .Release.Namespace }}.svc
  - {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "webhook-service" "context" $) }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "selfsigned-issuer" "context" $) }}
  secretName: webhook-server-cert
{{- end }}
