apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "k8s-operator-hermes-agent.controllerManagerLabels" . | nindent 4 }}
  name: {{ include "k8s-operator-hermes-agent.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "k8s-operator-hermes-agent.controllerManagerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
{{ include "k8s-operator-hermes-agent.controllerManagerLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        {{- if .Values.metrics.enabled }}
        - --metrics-bind-address=:8443
        {{- else }}
        - --metrics-bind-address=0
        {{- end }}
        - --health-probe-bind-address=:8081
        {{- if .Values.leaderElection.enabled }}
        - --leader-elect
        {{- end }}
        {{- if include "k8s-operator-hermes-agent.metricsTLSManaged" . }}
        - --metrics-cert-path=/tmp/k8s-metrics-server/metrics-certs
        {{- end }}
        {{- if include "k8s-operator-hermes-agent.webhookTLSManaged" . }}
        - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
        {{- end }}
        command:
        - /manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ENABLE_WEBHOOKS
          {{- if include "k8s-operator-hermes-agent.webhookTLSManaged" . }}
          value: "true"
          {{- else }}
          value: "false"
          {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        {{- if include "k8s-operator-hermes-agent.webhookTLSManaged" . }}
        - containerPort: {{ .Values.webhook.port }}
          name: webhook-server
          protocol: TCP
        {{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 10 }}
          {{- else }}
          {}
          {{- end }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        volumeMounts:
        {{- if include "k8s-operator-hermes-agent.metricsTLSManaged" . }}
        - mountPath: /tmp/k8s-metrics-server/metrics-certs
          name: metrics-certs
          readOnly: true
        {{- end }}
        {{- if include "k8s-operator-hermes-agent.webhookTLSManaged" . }}
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-certs
          readOnly: true
        {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "k8s-operator-hermes-agent.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      {{- if include "k8s-operator-hermes-agent.metricsTLSManaged" . }}
      - name: metrics-certs
        secret:
          secretName: {{ include "k8s-operator-hermes-agent.metricsServingCertificateSecretName" . }}
      {{- end }}
      {{- if include "k8s-operator-hermes-agent.webhookTLSManaged" . }}
      - name: webhook-certs
        secret:
          secretName: webhook-server-cert
      {{- end }}
